### ISSUE TITLE
Forcing -Wall really neccesary?

### ISSUE THREAD

**Issue by cornytrace** [kcat/opendf#3]
Forcing -Wall is in my opinion not really necessary as it produces so much superfluous messages that it does not really help with anything.
If desired you can configure cmake when running from the commandline / gui it to add the -wall.

**Comment by kcat** [comment]
What superfluous messages are you seeing? I agree that certain warnings are more of an annoyance, but between -Wall and -Wextra (which I'm missing -Wextra, oops), most of more helpful than not. It builds cleanly (without warnings) for me with `-Wall -Wextra -Wno-unused-parameters` on Clang 3.5.0. What warnings are you seeing?

**Comment by cornytrace** [comment]
in MSVC, the build log is spammed by TONS of warnings which come from the standard library itself!
Also, there is information like "variable blah is not byte-aligned" etc, which have absolutely no use for us. In my windows-compat branch, shall i exclude MSVC from using the -wall option?

**Comment by kcat** [comment]
> shall i exclude MSVC from using the -wall option?

Sure. I'm surprised MSVC actually accepts -Wall to be honest, so I guess it's being unnecessarily more verbose than GCC/Clang's. I wonder if it understand -Wextra too.
